### ISSUE TITLE
warning in opening notebooks

### ISSUE THREAD

**Issue by jonathanlilly** [JuliaOcean/OceanRobots.jl#120]
I had the following warning in opening the notebooks locally... I'm using the current release of Julia, 1.11.1

┌ Info: Operation failed. Updating registries and trying again...
│   exception =
│    Unsatisfiable requirements detected for package Statistics [10745b16]:
│     Statistics [10745b16] log:
│     ├─possible versions are: 1.11.0 - 1.11.1 or uninstalled
└     └─restricted to versions 1.10.0 by an explicit requirement — no versions left
    Updating registry at `~/.julia/registries/General.toml`
┌ Warning: Operation failed. Removing Manifest and trying again...
│   exception =
│    Unsatisfiable requirements detected for package Statistics [10745b16]:
│     Statistics [10745b16] log:
│     ├─possible versions are: 1.11.0 - 1.11.1 or uninstalled
│     └─restricted to versions 1.10.0 by an explicit requirement — no versions left

**Comment by gaelforget** [comment]
Thanks for reporting this but that's normal behavior I would say. 

Since I have [updated the notebook environments on Julia 1.11](https://github.com/JuliaOcean/OceanRobots.jl/commit/4b3193afa785576551883360a76e76c4d1540d54) you should no longer see the warning. However, users of Julia 1.10 would now get this warning I think. 

There can only be one environment in each notebook. But this is generally benign, so that's ok.
